---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vmauth.yaml
  - ./vmusers.yaml
  - ./tokens.sops.yaml
  - ./httproute.yaml
  - ./networkpolicy.yaml
  - ./alerts.yaml
