---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage

components:
  - ../../components/pod-quota

resources:
  - ./namespace.yaml
  - ./middleware-kanidm-oidc.yaml
  - ./homepage/ks.yaml
