apiVersion: v1
kind: Secret
metadata:
    name: digikey-mcp-secrets
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:y3hf1NJgX+70NRPpGXDiXw4nWw1OGgGvIc8z1kCyzjKwo24LAE9SkDMWtm1q1dx+,iv:eKghBAsCsqaOLi8HOVr4t+citUbV+8eIGElT209V5Ss=,tag:JJvNZwBOjRuHCN952K5+LA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:WBm9j3o3EK0DTMVa0wLwwASkhnScxIrVgqEowzFLRNEEjF375BVZOYVFcz3HWftwXDRDDTwVjo5jsEupxvdrKw==,iv:VMMr2r4aWWwAg3cKcda0Ne+pjEVsD03vG9/KK+diXgs=,tag:mZyf1Ft5L+MGZe9cbfSpbw==,type:str]
    DIGIKEY_REFRESH_TOKEN_SEED: ENC[AES256_GCM,data:RPmB3FTisSUyW//RfBhAto6nWe4fW3KKehQEYjRHE0Q=,iv:yJaorCCV7dYuBnOP5mArFUOsAOlvUlTdAzg1vg4uR68=,tag:euGutOwY4tD0E1y8vveBKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbmxqbnUzbDhkMlpxdzNn
            VVE4MUFJN3I2YVp5QjlldWJsc0I2SUx2aWtBClBkRXZTeHJ1S0ZHcVJxdmdNRkJ0
            NmkzaVBvWWM2RWRCRksreUxrcld0MncKLS0tIElhQ0VPNEFOcGhQQjI2Q0hSK1Q3
            VDVSRGU3VjFJRzQxQTRlYlZ1WGpsNjAK0kWQjy5TDMgd0QSlfkkb4sjODkFZB443
            CRsJnh/bDPqUaVEfTw8UXLA+fQ+Dhve7EMEXV0pfNWpsE0N/T4p6eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T02:29:35Z"
    mac: ENC[AES256_GCM,data:d9m1YEYLawi2drtEw82Q1ejjqWtzFb97omBka2vkYfNCrrnFfG1SO3XnHFZZP4Ly4ZtmgsCGd/ZP8AlMtGpBc4w1/Agd417W5JDZOVN1XaDfZOIs5vnI2v4GQcV99nEIWjRB7ntUmUge11bl2E5a6viOrIebGznwejsm3NyTdBo=,iv:Xp/yGL4nEKsv8TohPNzgLAuylSrEuKufNrQ8XDdMHGc=,tag:jlHkeWXdtLPUHG5ujpKkKQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
