apiVersion: v1
kind: Secret
metadata:
  name: digikey-mcp-secrets
stringData:
  CLIENT_ID: ENC[AES256_GCM,data:y3hf1NJgX+70NRPpGXDiXw4nWw1OGgGvIc8z1kCyzjKwo24LAE9SkDMWtm1q1dx+,iv:eKghBAsCsqaOLi8HOVr4t+citUbV+8eIGElT209V5Ss=,tag:JJvNZwBOjRuHCN952K5+LA==,type:str]
  CLIENT_SECRET: ENC[AES256_GCM,data:WBm9j3o3EK0DTMVa0wLwwASkhnScxIrVgqEowzFLRNEEjF375BVZOYVFcz3HWftwXDRDDTwVjo5jsEupxvdrKw==,iv:VMMr2r4aWWwAg3cKcda0Ne+pjEVsD03vG9/KK+diXgs=,tag:mZyf1Ft5L+MGZe9cbfSpbw==,type:str]
  DIGIKEY_REFRESH_TOKEN_SEED: ENC[AES256_GCM,data:M1HWqj9ah8XN+DCfUU9adCRJyrQaKv9KQmkjkCn2fiQ=,iv:kyiYa/rpLe7bYFOOGMAjaJXIftGg9cAvif/TLf8Y+lk=,tag:vrokOfiesIhv0bnnexO6Dw==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbmxqbnUzbDhkMlpxdzNn
        VVE4MUFJN3I2YVp5QjlldWJsc0I2SUx2aWtBClBkRXZTeHJ1S0ZHcVJxdmdNRkJ0
        NmkzaVBvWWM2RWRCRksreUxrcld0MncKLS0tIElhQ0VPNEFOcGhQQjI2Q0hSK1Q3
        VDVSRGU3VjFJRzQxQTRlYlZ1WGpsNjAK0kWQjy5TDMgd0QSlfkkb4sjODkFZB443
        CRsJnh/bDPqUaVEfTw8UXLA+fQ+Dhve7EMEXV0pfNWpsE0N/T4p6eA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-31T01:50:13Z"
  mac: ENC[AES256_GCM,data:5BVxLYI6vMfi8oU7fZkweo1rdK0eE/y6cw8V9nLD+NcME4wlSqVuTnkB1G4nd4/qvEoROlrPv+9WMhu70z/6CiUnwK5kc5FJLCMxtyuitYnJtJsqejBEslLfBe7Zcf+FBR7XpNz1CvrabE4lCIPrFMEKH1UBYrMIGPodNT6dg+Q=,iv:Qzv/5l6Z4tNh3C7aDLEwzM2lbdldFIC4W3JOYLOdpDY=,tag:d63+PKdZRZ3rCgy2RtT3VQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
