---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./datasources.yaml
  - ./httproute.yaml
  - ./alertmanager-config.sops.yaml
  - ./alerts.yaml
  - ./platform-alerts.yaml
