apiVersion: v1
kind: Secret
metadata:
    name: kanidm-bootstrap
stringData:
    #ENC[AES256_GCM,data:Fogc2kek0lMN7Iz4F00+TxeYqGH7CNWOLF2711RI0goS9Q7CSZczhx+/rUiZu6m0aXh1ebjoDiqR9kC4XDlqhBmNUZtYHFE=,iv:NMWaApoX9jekgod3QUKN4Ao8iTkwefNOeGhhWaiyufE=,tag:piLu/6FkxVoAD19F5WBcYw==,type:comment]
    #ENC[AES256_GCM,data:LDzjIGclvyLkT4s/eYHa/RR0RzyTCD4pylEMeO7YwG5MCfIhSbme2rNUdQqx6LLAosBG4x3bdD36,iv:iTdc/jh9RgzqL7Gz5Z68ZC3ky/13I6m1v3R0Epayox4=,tag:zbjVKoFYZmwrMLvkBXGDeQ==,type:comment]
    idm_admin_password: ENC[AES256_GCM,data:SlqnQL9TnvZPSp2pj+8iYWQHPofxIgbp9C3JyQDwKh4gFusBYG+cHWornG0tMZzv,iv:wIZj11CEDGHQgI+kzrMKMAYjtccD3ea29eR1eiCEjbg=,tag:+v8OlA+Bsl/nxMs8lUslHg==,type:str]
    #ENC[AES256_GCM,data:VxeXGi82p05MiRIkMgi7ZfEk+6Dcw1h7BvLyqhcOA5wFYue6J/9IIHvMg2blzuiKBpQK/JZM/s0RbNDkPeoJs/Fl6kpJ4A==,iv:bi4fgDYcLWaHEV1O0yqYeeiS3y7senxc9Nrk8Psk7WU=,tag:fVmIPRzozBLrhdOFuKl4iQ==,type:comment]
    #ENC[AES256_GCM,data:V9Pc8DTlaQUGELHkDUj1GWbk1/yinzSuVP48roavKlPpXn2Jjzl+B6WTs23tbDBcUuqxgePnpfJnYTunLxs6olp71w==,iv:JS7ZoLNcmm+NyZ0kHHwPWrJueoLw35OITZXNAN7dQQI=,tag:Lc3iD5zExjd33J818xF7Ig==,type:comment]
    #ENC[AES256_GCM,data:rqwAoYWW7hHSzr4NtcHck1qP1fwzI1Fadqrs7tkCMSsxTilaVw==,iv:9x5qkOzodmqMJPXra0+Hje9ytxO1CV/bzTlbR+l6vw8=,tag:glKABSH/r7uf+/DMs1BQxQ==,type:comment]
    admin_password: ENC[AES256_GCM,data:phf6VC49/9aW6+M8i6WcLSw6UvYkXmm/ozZu/72diBV+D4XxBQ==,iv:aJOcxdUX7FcCGCJt0qnVvIVG/0vOu0HQ7zSUfFu36yI=,tag:Oex/8vChlkqWwmGDK4rMAg==,type:str]
sops:
    age:
        - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NjA2cTFLRGVTZW44VUdH
            Wk14OEZBUSszTVo1R3VDK3FMYU9WeGtBR1NrCjlCRVMrK0E0VmNjdGQ1RUN6RFNR
            MzRRcGNNYzZWQm03WGkvZUd3dHk1bWcKLS0tIFJDa1d0b0dlUjg5QldlUTkxVGYx
            ek5ORXlacDF5QUpJQytHMzV4TklCbUUKX4OO2/qzI5rtQ2VMNRhGm+xdd1/vcHIS
            5zy4GsZaiKcGSopU67Kt5HZfN0l2QZXyfW8LQh716x9U35neCtjmUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T02:44:30Z"
    mac: ENC[AES256_GCM,data:4NcaBe5XMtyCtOAOzPcN0LbqNl4er3yuChBzW3meOrnB6i5acUpeN0E1eRrNE+Oo9yIZRm2+9G5oEuqnaUl0QTjNY/nVQK0J2eAsnHOCpWIh9JZBsjALZEJKUeSuN0SEaHcduqYLFNrsjbPahmJayrD3VV2vUgLJM9p9/nUTP9k=,iv:e3P/pdq+ZbldKvxFJOokq0PhBl+Je4r8XBqU6gRNc9k=,tag:z6rfaNMU2+FzMyvp7QMpBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
