---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  interval: 1h
  values:
    fullnameOverride: k8s-gateway
    domain: "kelch.io"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      useTcp: true
      labels:
        lb-pool: admin-prod
      annotations:
        lbipam.cilium.io/ips: "10.32.130.2"
      externalTrafficPolicy: Cluster
    watchedResources: ["HTTPRoute", "Service"]
    replicaCount: 2
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        nodeTaintsPolicy: Honor
        matchLabelKeys:
          - pod-template-hash
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: k8s-gateway
            app.kubernetes.io/instance: k8s-gateway
