---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./middleware-kanidm-oidc.yaml
  - ./storage/ks.yaml
  - ./prowlarr/ks.yaml
  - ./flaresolverr/ks.yaml
