name: monitoring
working_dir: sparks/monitoring
compose_files:
  - compose.yaml
prune_images: false
reconciliation: false
---
name: monitoring-gpu
working_dir: sparks/monitoring/gpu
prune_images: false
reconciliation: false
