{
 "title": "VictoriaMetrics - Alert statistics",
 "description": "Overview of alerts state in time based on metrics generated by VictoriaMetrics vmalert.",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vm_app_version{version=~\"^vmalert.*\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(vmalert_iteration_duration_seconds{}, group)"
    }
   },
   { "name": "topk", "query": "5, 10, 20, 30, 50" }
  ]
 },
 "panels": [
  {
   "title": "Firing state of alerting rules on timeline",
   "type": "state-timeline",
   "description": "Shows the state of alerts on the selected time interval.\n\n Color represents the frequency of state changes: red is frequent, green is no state changes.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(topk_max($topk, sum(vmalert_alerts_firing{job=~\"$job\",instance=~\"$instance\",group=~\"$group\"}) by (alertname)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerting groups",
   "type": "stat",
   "description": "Shows the total number of loaded alerting rules across selected instances and groups.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(vmalert_alerting_rules_errors_total{job=~\"$job\",instance=~\"$instance\",group=~\"$group\"}) by (group))"
    }
   ]
  },
  {
   "title": "Alerting rules",
   "type": "stat",
   "description": "Shows the total number of loaded alerting rules across selected instances and groups.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vmalert_alerting_rules_errors_total{job=~\"$job\",instance=~\"$instance\",group=~\"$group\"})"
    }
   ]
  },
  {
   "title": "Alerting pending",
   "type": "stat",
   "description": "Shows the total number of pendings alerts in selected instances and grouping groups.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vmalert_alerts_pending{job=~\"$job\",instance=~\"$instance\",group=~\"$group\"})"
    }
   ]
  },
  {
   "title": "Alerting firing",
   "type": "stat",
   "description": "Shows the total number of firing alerts in selected instances and grouping groups.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vmalert_alerts_firing{job=~\"$job\",instance=~\"$instance\",group=~\"$group\"})"
    }
   ]
  },
  {
   "title": "FIRING over time by group",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk_max(100, sum(increases_over_time(vmalert_alerts_firing{job=~\"$job\",instance=~\"$instance\",group=~\"$group\"}[$__range])) by(group) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FIRING over time by rule",
   "type": "table",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "topk_max($topk, sum(increases_over_time(vmalert_alerts_firing{job=~\"$job\",instance=~\"$instance\",group=~\"$group\"}[$__range])) by (group, alertname) > 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}