apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bakeoff-ui-htpasswd
data:
  users: ENC[AES256_GCM,data:H41sjCgoYYGGfwBUdiappJLzNSIu2ptEKvPx1GOcA41OWR2hFjdVE5wp7tpWQz5IcOEn6B8g13OECuXsYjXiQ6sRGohmKfy97xHnUM0wMCOcLgBw/b7eDOFQEFo=,iv:KMhSQ2vshY1yVd/j50B32OfMm2yrhSoRozYfJU13dzU=,tag:qECiHO0qdzUddkUE5CsA1Q==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcVBpNUdqYmhseEZmMFkw
        ajV2alJRZ3MwYkJFR0VTbjdCSG9uREViUW0wCkY2ejd6K3h3TWszajFHZFoxYkRu
        NXMrM09GZEVnNGxUd2lPYXBHeERkMGMKLS0tIGNBdnBKZkgzQWJMc3g3YkllbG9m
        ckZZS0FBZXBzSGhNM3dCenRiR3JXMkUKZOXA3lDMlXtdMvF2hpub0uxIxeMeFwI4
        29jCnlDyp6mrM1Vv842mcul1WcN0JYVCZBfw6tPKDSAdvM0rMtQoNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T18:23:51Z"
  mac: ENC[AES256_GCM,data:0Y0kXns/53hyikyBLC+QKkl5Su5lsmdXA05ehH4k1npLOlOzCQqC0LWYJ9QneHEQHLPjCeAuVIoepDwr8Eyyq+X0X7HmRmO8PsFkcdAr5F1TCE2iAcHUZ+rLkgn2oVOokOq0jU8Oc7xvuCHZAR8VeQaiXmAB4FAbQD/sk/GzYeY=,iv:qq7OL0/oJkY6LwFgJePiEMmfQL9o98ArtfxDxoNx8DY=,tag:FpiXYoamUHXSDh/Qr/EgZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
