apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZqSOgHjJxDh1PstwXAh5QQQC9Cc+cjcIiZrlu42UKS8KIYn837QDr5OMQdHy77+t70h+8B8=,iv:GRQZHj+84mVDE/2AAup1WY6aEfLlxwTE50jODGW48+A=,tag:Jm6PKiHFlO5ebFgK4jCzyA==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUEtOcTQ1T25xZnh3ZU9C
        dncwMXorVXozODBUSjJLR25uMFZOZHlQUjBNCkZLSkZVekhKZm53TUN0ZEtZL2dQ
        M3FHSlJrVmlTeEdNTURSZ0h2REVnSEUKLS0tIHpSK2s3OFBwb3Z1bzB0dDA1WlFD
        bFdERFdnZjZydHBQb0RxT21ZZnR1T2sKDivhaa0O+TzGQWR6P/A4bH17KL56CgUg
        oirtJJSyUBUjN+RmK8K3b6kuIOzo2iozscbp5o8LYCRzowfyek92Tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T23:34:25Z"
  mac: ENC[AES256_GCM,data:aYN//TVh5BDrm8XF+0eD5xM4hvs0U9wjM3nLya2wGoiOQeRQ1rF870ki8jH6EHhddJMI3As2LyJ3EaUwIpiSaWiNbCQSrng/nPnSk/we/ZVlos3vilfyKNatmbRogl3PNJOmIUUdu69FhCSpLwknEMNnSF0zyuB/OMfcEU23N5M=,iv:2+OcACPgKPKHCnjWzIovFjk2bIY6IksGPcf3SO5hWz4=,tag:f55QDzpUt798LTdZvGeWTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
