apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:8GR3059eTojTUwI2EVF5sFrLLVxOqGUVYapWlXwoOpNkKGrCZtwQDJvYTz8+AY4Y4fWnMyY=,iv:7vJ0ihr4uZsrotNIKPLKHwFApgdQ1pFxMKHEyqIJEX4=,tag:1CdBNInNhkY5dosCgrBZ9g==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eVAxb0dDMUZDbjRjM1dl
        S3B1WGJ6MDBmMFBqcGpzTzhXS0dKT3VrQlNvCnIzZ1NpcG44VHoveitYTWVWTW0w
        TUd2dDlQU2hXZ2pHdzlVU0QrOWRKVUUKLS0tIDY3YjJsV1diWm1IVWtrd3Z0M0VM
        UDBLY055b3gvdEJ0bTZNQ3pNa0tGZDgKkEGOl0M4OP0ZDdpALhFzrDt7zL41KtSZ
        SVMJdZBuamsbj2Kp91JB+vuQIauExfiWdhkhclMiuycIXNgvyhYMVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T22:41:40Z"
  mac: ENC[AES256_GCM,data:BKkfy/pTghgrqt8EP7uTH0rtEZiycGLBAbgKhlt3GId4HiGTbsTdVvfBkpvqYY5z9uekBWoudnCVKHBxPNg/ihnxzMbGUz+GAZlHxXd5lS4++CLWJJD3GK9lFJs0oFCuLxpyYD04Z5l57z8iQ2srrDCTWFuYYOSKFegCAsF0Qs4=,iv:CvC51GqsmorkH4TzkjOjZKENvWvJkwI+y32opRESnbw=,tag:JGBp9DsTsgBTlMexcCh3Rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
