apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:TbQ4kOWPkW0=,iv:T5ou5byMmwZ10EN08zhidi/vFnC5iUM9tnYz8UQWHEI=,tag:IazMlibVRPe63HWdMaW+8g==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cFZmaWlsK3ZqQzRCZHRo
        NW5PYmNYYzViQVdkdE1vamhtVXJWdTc5VFVRCmx2di9FZElBbi93RGo1VTVDb0FN
        ZTZheEpySUN2ZFNPVzBYaGE3cHVwUmcKLS0tIEpPSHFZNUF3UnhVRDJYTW9hY29L
        TkJXdDZ6L2VUYU1uSktzOWRYeEpQUGcK+TKaNHYJz64ySm3LPszBpGzvYdmyztXW
        44VQCduiFNZh38fSBU70Z7T9d7uExBK4r/v6AI1dHxbGAS6BBcEUuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T22:41:40Z"
  mac: ENC[AES256_GCM,data:9E7PJQSPuMGbZ5kHxyTgRe+AmVszBUb+YPW5n2rddQJqkKQ6pgS0aXqCv1qWtjLiiXRucw8AJ58XBTymZIzK1yljG7v5U66TmBSb7/ETuumwNTKDJJmNDdiyqq8fukE4uAYSfozE0BIM4JPBdgPkIV91fiSxMNrbLurC3q4qMFc=,iv:mBea7Z9aJLbIGOKgcU/45js9zcUh4qzDqCtGzme+Mzs=,tag:e/sdlwgwwEZyNVXRMZGqsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
