apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:mVfhykSrKMs=,iv:WZVBFfccX7txrBJtWbGZ1UsEeRakqc9r3Ojl/rxxasM=,tag:up9WijKLXeUyvmnG2Fblcg==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQnMrZHpaS1B1ZEJDTTc0
        RUhpbkhpaFR5QnJEcXlJM3JiUGFJMEdvVWtBCjRrMFlncGNaeGFlNStZeEo1WEIr
        L0VBRWwyOUx0NDBmQmtwNkRJVHhlSjAKLS0tIDZUV09TQjN3dFRucjVzVTd1ZENK
        VTJITmdsbnowRlRpTGo0YUdPd0l2V00KHw1esj9Yw1QPphIyBn1LQV2d4D9QqbmZ
        2rdmu9Sua1EQ3BfTWqO+th3xfRB0yHZevfmj8u9D1FaS1YIaxi8ncA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T23:34:25Z"
  mac: ENC[AES256_GCM,data:4dIyzgSehQSp34PlbcsWUtrjeOkGJgRjeSSmIWf355csUyVx125vcPiKHtdInC6qGVLIRiNMUZHKVS5ppH4x8NI+DnIAo+d2Bium1ZmdPWz4OFOKy43AWxIpx8BYpqsJkQ9p9BP51vsD+I5POYrk2htpYJ1Gil2QjtoYegQLtYA=,iv:yylcdlspBZHKHhLH8Ef9THk/AUn688mzu9dJCTJEh/Q=,tag:6VGNju1+YjFoEFmeHl4Z4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
