apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:8Lbz66z97lCEctat4LJ1tr0gwpYyhcF07+LPh8pMp5Q=,iv:uaB4JodZem++zMaZP26w5e1Hp6pPmRIkgyO3Yknr2nM=,tag:9rul4o69w6WIhTwITcN1Mw==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlczBmMUczVzVDbnd6RnlH
        YjFsWmptNDVrMmU1bVNXZTlNTll6aEpNaVhjClI3TkFEWHV1UnVkbW9rSVdJdGFx
        WHFzamk5cEFYUHUvRkZ4bWQ5aHJ5SDgKLS0tIGVaamNsbTA0djQ0YWQzOEdFamR5
        ZmRvMnFkU09kNjBpbTFjbXQyR2xFVTQKf9C0EWD++FD3to5cUgV4H+CM6Vj76RJW
        MUHJmiBB/ZROtVMzYCmZLjvmcqkNpeBxOxPppdz6FO2yZ+6C3bbptQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T23:34:25Z"
  mac: ENC[AES256_GCM,data:Wdw0/myGyBlT14Wirt8689jt1Uz6NqNImd+xk0gI/EAqZnxC/53WOOokkdxXd/c87RjCj8bihjTlF2kU02DBimTUh7VYNpsZSWURJalsegxd2jZ7fAnkpjrEdKbyUtQ0cD7cqiZ5CflDChklFl1HPUr75vMzWfOJwK8ImwoVXE4=,iv:yPsfgmq68H86gd5EJrIHD4EwZER1h2P6QdBs+tS7UnQ=,tag:8Ks/sPymNks4sGQZKQvtRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
