apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TzcLK4ZL4h8C9nHx7gzRdbQH3iHUENd7GJ2JL8bkfwo=,iv:BCdtAny2VbvTWbw3CmQgo6Gr8phj1sHb8613tuCL4cA=,tag:G+SZ54OEz+q1eCidXJ5ECA==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVUZYUktYcDJyK3JBVUlW
        NEJ0dUtqVGUxaXpWajZSSm55VmVsYVJ6eUh3CldmazEram9Nb2p6ai9FOUF6NFZB
        TTBQci82Sm9Sd3NlS2lxc3M5czlBdnMKLS0tIHlVSVgvbE5JSUg4djhjRmhwdjBz
        TXNyYm51dWVXL1BPTTYxc2VESTZUVXcKEj/n7Ane+6GczyUdx5hsJx4THSTskfFt
        Z4dt6RFxDmmKH33la4oqQbrgTu0fvmGOdttYi1GcrJFwzxC9VvJaYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T22:41:40Z"
  mac: ENC[AES256_GCM,data:x0nJNMBW/ZL+ZMdtqG9GSsK6oLOA7Q2VNkNYMnUh4S5eVQ5OaeJwnwgdqzquulJqm1avcIjKsQPvcsFbLr/50NKdRe0jYxUdX4lTnV7X6ATdiN/ZIxbUNBNgr9lChzK4OmC0d/mmQn0zeSZavEUNNX6korPt4/dA2xFliQ9wHes=,iv:WohFTKi9dxDX1Dbjw+gpAz7WRhlJydIxfe/SU/nwGn4=,tag:fempNtBNU8BlgSR9AZIKww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
