apiVersion: v1
kind: Secret
metadata:
  name: pve-exporter-credentials
stringData:
  PVE_TOKEN_VALUE: ENC[AES256_GCM,data:o7gzs0Eg4/oWWqdBF5mB9OSMJfoyb5k8hrmZPYz4eawHCWZT,iv:cklv5L1PgZKoGdsjQLEJwe9OEXhOltxr2x8rnPibRIM=,tag:NIwCz3yQrcYnDYoeQnT3vA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMHhKdVdLNENvSkd6M2ZH
        WnRRNmZpakV6MS9HcTJyNUtMcE5zakY5bWdNClU2WE1HTDhvbUNEUVlOakdGY0pM
        SmJLb3VLQUNhRlg4TW8yNGFUY2pJSFEKLS0tIHJ2UVJaL3M1WFBuQkMxUTFob254
        UmJ1bXh0WG1HUUMrbUNFVE85UlhSRkkK6Gv7vTe4iJjnncAXZWQGC8nZW+re7YfM
        z2JTJLuJ+sWRa0s16xA+dZN5B4qiMygDgn/wpLYGzO50A+qIVWRfrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T04:54:30Z"
  mac: ENC[AES256_GCM,data:WKSzQomyFvrFqo3XLLUVOBGEtcu04QaoS4Y6p1rL+SeXyNBYIat+4aIc66biTiX02+rNTJeTun8/xLRgDP88GepY2PUeuSAdbK/jGR5ZpQYsVdqFKQY8hnRAV8bBxrpx4mzGQklCGQ7mM4Q19G0qtxKr2k7XGVcLKgZhf1YcIQ8=,iv:8zwOBM5L9HEbCvOoAcyaOE9jP9wexYNB8Uy4ak0Ve0w=,tag:S0ra8ylUrwNuH8Xf+aAS3w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
