---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./credentials.sops.yaml
  - ./deployment.yaml
  - ./networkpolicy.yaml
  - ./scrape.yaml
  - ./alerts.yaml
  - ./backup-alerts.yaml
