apiVersion: v1
kind: Secret
metadata:
  name: openobserve-root
type: Opaque
stringData:
  ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:9G+DoEPvu1ngegIbTwc4yQ==,iv:dgH35OyLSaALacMW4Sd8DXpdtcCRZWjY8HBgeChO7o4=,tag:eYNNkO6qs2DD9i/a9oyUZQ==,type:str]
  ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:5prl0ll+ndnEEG8832xWnR1sEYSmMoTArb5oXXjy8/M=,iv:9Z879SXzTHtYrejAHJ3wl8p8AREzxXopwqE7dpQOBWM=,tag:8emeu38kKIBe42qDVGZycg==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K1NJc3lPVkRLZ2JyYjRF
        bFIwU3FDWjQ4ZnJQOG44SHdkMWoyQm5QY2kwCmlmUmU5Y2JMV2xnZzVpRitSQ2Jz
        NW1DakVTZE13cWNYUkxxRy85dHllOEEKLS0tIFY1bjZYaTJGVm0zL3huR3ZSMlFU
        N0ozai9wZ0d4VnpkRjFEWktkeVJSWTgKoqqQ1u8y7yN58IbFIhotq+93+trZS349
        yxsvMGkR3w0YQAmp/UbaOCASKiOjN3b6t2ya4NfMzGV4iHNYqzsjAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T21:44:25Z"
  mac: ENC[AES256_GCM,data:oT6CguwOwezi8cP8f9/KhVGgEgDCBs+tBpLiCPCsahJ/A2HF/3dOMzpofzoCbPEeSGUXFxl5BvfFE0HXeRknGzWMn+BpQp7c8AFB6Hyc84tzleo/Z6oSnMGvXGGIk8m2pkIVtP6ja0X08ekpSYPEmpdttilo5QzQuwLVTHFgf0w=,iv:5okiUgDyEB6A/jr6h79y6femIK2j15iDzFJADRs79Es=,tag:a4aDnb7jUkNTCv4RExNCxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
