---
# Victoria Logs policy declares cross-namespace flows only.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: victoria-logs-single
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: victoria-logs-single
      app.kubernetes.io/name: victoria-logs-single
      app.kubernetes.io/component: server
  ingress:
    # Traefik admin query access.
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: network
            app.kubernetes.io/instance: traefik-admin-network
            io.cilium.k8s.policy.serviceaccount: traefik-admin
      toPorts:
        - ports:
            - port: "9428"
              protocol: TCP
          rules:
            http:
              - method: GET
                path: "/select/.*"
              - method: POST
                path: "/select/.*"
