apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:l+9HJ32ZCKZU77oXeYpVaANnwOFGuYeZdetHdXBpW+B51U+hx+xCNem+tzc=,iv:tqH0ZMkI6yLcbZPbSQNPxF/sZCyP9TQKmOSxJ7+2VII=,tag:lBq4+s5ST6Mhevsf1quVEQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:zV2rM47y6BMUdWGZI5rugP7RFRtUCgM5ZRszCgcJuw==,iv:9spYKqEECFphAWwHCwZgLLrBqp2jVJUgnIDcsAbW7/M=,tag:MVOD1hPmpoY0XkK+Ju0NDg==,type:str]
    WEBUI_PASSWORD_PBKDF2: ENC[AES256_GCM,data:QH3Vx7w2oVYlJYtzdFqRVJuPKlaOBiJqTPNO7Le7z6tQBEw9h9awZAUVJEqHJisP/rvUCZRLL6zbBkBJ9QlT5GuDEy66Hce6xHoWsjbk2CpwXMR1BbuABRyHXtsGePHI6/JwNH1PHxHrTeSSPiEllxg=,iv:owseaQCBhxlMx9NRQ8edni7nvlYxp45fuPzPUhPWT6Y=,tag:wV2Z8yNHZL0+JpA6ieQX6Q==,type:str]
sops:
    age:
        - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVlZ2dER1MDNRSzRNaWNE
            Y0hVcnJFaUxXei9ESnVZSFFMZnRuZVFDWDFVClp3Q25oenQvRytydzhEK1lJamVY
            enlWYkVwU2lxY1JSay9YRDNYdWQ5ZEkKLS0tIDc4UDg0UG0vQmpLVkExQ2ZlVjFR
            aHgxMGdwaXVLN2ZGQzZWUHR0cGlUYUUKoQQwZANfUr1j3dd5G5X4joYL2oEqSOpg
            0CFD7u6zSw0679lGwMXGlYRnsgleW1EjG63OFvRQvVI01M5cX+cb7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T13:21:55Z"
    mac: ENC[AES256_GCM,data:wtSpzkjdI/9qklkNlH8u02N1gFyqwXfFxW7/FbIGcY2jEmXO5bpZ/YLEy7AU2K4m07zBu5I+k0gU9VG79FlyZmzPHG4DP2chhz0g3lRwWivXRVrIOtXF+P+rB781C+mOF1a9YGrLmz2LHD/0CPi4lAUEVx4kgSq9B6zuk4yGdOM=,iv:zJC7mVSqOlIWEOC8dTTE+0XSuPWGZydAzCfBlLOnLg4=,tag:+CuVGPY3JuZ/0Xz51B5vAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
