{
 "title": "Flux Kubernetes API Performance",
 "tags": [ "flux" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "flux_operator_info" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, flux_instance_info{namespace=\"$namespace\",kind=\"FluxInstance\"})",
     "legendFormat": "Flux {{revision}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "topk(1,kubernetes_build_info)", "legendFormat": "Kubernetes {{git_version}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"2..\",pod=~\".*(controller|operator).*\"}[5m]))",
     "legendFormat": "Flux Requests"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\"}[5m]))",
     "legendFormat": "API Requests"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(apiserver_request_duration_seconds_bucket{verb=~\"GET|LIST\"}[5m])))\n",
     "legendFormat": "API Read Latency"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_requests{verb=\"WATCH\"}) by (verb)",
     "legendFormat": "API Watches"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\",dry_run=\"All\"}[5m]))",
     "legendFormat": "Flux Drift Detection"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\",code=\"429\"}[5m])) by (code)",
     "legendFormat": "API Throttling"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(apiserver_request_duration_seconds_bucket{verb=~\"PATCH|POST|PUT\"}[5m])))\n",
     "legendFormat": "API Write Latency"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(apiserver_admission_controller_admission_duration_seconds_bucket[5m])))",
     "legendFormat": "API Admission Latency"
    }
   ]
  },
  { "title": "API Server Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=\"kubernetes\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memory_classes_total_bytes{service=\"kubernetes\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(process_cpu_seconds_total{service=\"kubernetes\"}[5m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memory_classes_total_bytes{service=\"kubernetes\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Server Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "API Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\"}[5m])) by (verb)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, verb) (rate(apiserver_request_duration_seconds_bucket{verb!=\"WATCH\",verb!=\"CONNECT\",verb!=\"DELETE\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Admission Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, name) (rate(apiserver_admission_controller_admission_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Flux Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Flux Operator Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"2..\",method=\"GET\",pod=~\".*flux-operator.*\"}[5m])) or vector(0)",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"2..\",method!=\"GET\",pod=~\".*flux-operator.*\"}[5m])) or vector(0)",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"5..|429\",pod=~\".*flux-operator.*\"}[5m])) or vector(0)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\".*source-controller.*\"}[5m]))\n  +\n  sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\".*source-controller.*\"}[5m]))\n)",
     "legendFormat": "Source Traffic"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=~\".*gitrepo.*\"}) + max(apiserver_storage_objects{resource=~\".*ocirepo.*\"}) + max(apiserver_storage_objects{resource=~\".*bucket.*\"}) + max(apiserver_storage_objects{resource=~\".*helmchart.*\"}) + max(apiserver_storage_objects{resource=~\".*helmrepo.*\"})",
     "legendFormat": "Source Resources"
    }
   ]
  },
  {
   "title": "Kustomize Controller Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"2..\",method=\"GET\",pod=~\".*kustomize-controller.*\"}[5m])) or vector(0)",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"2..\",method!=\"GET\",pod=~\".*kustomize-controller.*\"}[5m])) or vector(0)",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"5..|429\",pod=~\".*kustomize-controller.*\"}[5m])) or vector(0)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\".*kustomize-controller.*\"}[5m]))\n  +\n  sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\".*kustomize-controller.*\"}[5m]))\n)",
     "legendFormat": "Kustomize Traffic"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=~\".*kustomization.*\"})",
     "legendFormat": "Kustomize Resources"
    }
   ]
  },
  {
   "title": "Helm Controller Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"2..\",method=\"GET\",pod=~\".*helm-controller.*\"}[5m])) or vector(0)",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"2..\",method!=\"GET\",pod=~\".*helm-controller.*\"}[5m])) or vector(0)",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"5..|429\",pod=~\".*helm-controller.*\"}[5m])) or vector(0)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\".*helm-controller.*\"}[5m]))\n  +\n  sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\".*helm-controller.*\"}[5m]))\n)",
     "legendFormat": "Helm Traffic"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=~\".*helmrelease.*\"})",
     "legendFormat": "Helm Resources"
    }
   ]
  }
 ]
}