{
 "title": "Proxmox via Prometheus",
 "description": "Proxmox Virtual Environment Dashboard",
 "tags": [
  "Proxmox",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"})"
    },
    {
     "expr": "sum by (id) (pve_up{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on (id, instance) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"})"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on (id, instance) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"})"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on (id, instance) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"})"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",template!=\"1\"} / pve_memory_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on (id, instance) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"} and on (id) pve_up{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"}==1)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on (id, instance) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"})"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} / pve_disk_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on (id, instance) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",type=\"lxc\",instance=\"$instance.home.kelch.io\",node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "(pve_cpu_usage_ratio{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} * pve_cpu_usage_limit{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"}) and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_cpu_usage_limit{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_limit{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} / pve_memory_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} and on(id) pve_node_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",name=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"}) * on(id, instance) group_left(name, type) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"}) and on(id, instance) pve_up{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} / pve_memory_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} * on(id, instance) group_left(name, type) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"}) and on(id, instance) pve_up{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\", id=~\"storage/$instance/.+\"} / pve_disk_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} * on (id, instance) group_left(storage) pve_storage_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Space allocation",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\", id=~\"storage/$instance/.+\"} * on (id, instance) group_left(storage) pve_storage_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "LXC guests Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} / pve_disk_size_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} * on (id, instance) group_left(name, type) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",type=\"lxc\",instance=\"$instance.home.kelch.io\",node=\"$instance\"}",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"}[5m]) * on(id, instance) group_left(name, type) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"}) and on(id, instance) pve_up{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} == 1",
     "legendFormat": "{{name}} RECV ({{type}})"
    },
    {
     "expr": "(rate(pve_network_transmit_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"}[5m])* on(id, instance) group_left(name, type) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"}) and on(id, instance) pve_up{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} == 1",
     "legendFormat": "{{name}} SEND ({{type}})"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "((rate(pve_disk_write_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"}[5m]) + rate(pve_disk_read_bytes{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"}[5m])) * on(id, instance) group_left(name, type) pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\",node=\"$instance\"}) and on(id, instance) pve_up{job=\"pve-api\",cluster=\"pve-sbx\",instance=\"$instance.home.kelch.io\"} == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "API collectors available",
   "type": "stat",
   "description": "Number of responding Proxmox API scrape targets. Zero also covers completely absent targets.",
   "gridPos": { "x": 0, "y": 53, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"pve-api\",cluster=\"pve-sbx\"}) or vector(0)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Cluster quorum",
   "type": "stat",
   "description": "Minimum quorum status across API views of the cluster.",
   "gridPos": { "x": 8, "y": 53, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min by (id) (pve_up{job=\"pve-api\",cluster=\"pve-sbx\",id=~\"cluster/.*\"})",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Node online",
   "type": "stat",
   "description": "Minimum online status for each node across all API views.",
   "gridPos": { "x": 16, "y": 53, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min by (id) (pve_up{job=\"pve-api\",cluster=\"pve-sbx\",id=~\"node/.*\"})",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Required guest running",
   "type": "stat",
   "description": "Running status for guests configured to start on boot. Stopped templates without onboot are excluded.",
   "gridPos": { "x": 0, "y": 58, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (id) (pve_up{job=\"pve-api\",cluster=\"pve-sbx\",id=~\"(qemu|lxc)/.*\"}) and on (id) (max by (id) (pve_onboot_status{job=\"pve-api\",cluster=\"pve-sbx\"}) == 1)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Persistent guest missing backup selection",
   "type": "stat",
   "description": "One means a persistent guest is not selected by a backup job. This does not verify backup execution or restoreability.",
   "gridPos": { "x": 8, "y": 58, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(max by (id) (pve_not_backed_up_info{job=\"pve-api\",cluster=\"pve-sbx\"}) and on (id) max by (id) (pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",template=\"0\",tags=~\"(.*;)?persistent(;.*)?\"})) or on (id) (0 * max by (id) (pve_guest_info{job=\"pve-api\",cluster=\"pve-sbx\",template=\"0\",tags=~\"(.*;)?persistent(;.*)?\"}))",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}