apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:/KGMZYk=,iv:xYa+lHcjYmJfR4ISNL7i4QaTYtg3uu8RufzcezxGcMs=,tag:R2Uz0PYK0VJ2tYG7g1JvuA==,type:str]
  admin-password: ENC[AES256_GCM,data:O+yBxNRz6Unn1T/NTj1M7N+nY598e2ty8CPunY7ymYE=,iv:2WjkdJvE6i0j1c49/+Zy9gyElnJmf4eAwLPZgdN+Jag=,tag:6/KZPLldVx70HPXbmvQDEw==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTnZPUkNmaEFCcm0zOUNl
        eGNqUGZDYXBWOVFSSGhsK0lsNFdyWHJ6RTE4Cld0L1RYdmNOQUlQRzRJc1RGalk3
        S3JFRmVnTk4yTndZZ0tRUjJFRWUzblUKLS0tIHV4Qi82RWNVTFhEWUVqSEw3ODdV
        TWtPZ0Vzc21IQ2szOEpkN01TRXIxRG8KF8K2VsLfMNDF8TA0quN4Xk1dPrLumfrQ
        ClFHoEhLNZYw+HI8nHOkvRAlhEXhkwxhvU7tX1+a3C6zMLqIlJuFIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T16:25:46Z"
  mac: ENC[AES256_GCM,data:Ej96SE5vC6KyjK1fBwZUqxPAnuxfX+ocP0dnMr2vxGpHt3FqSUWYlJdPF6YAz/rOCZva5HetAkW+fGH93xtkpf9q+ZRFMwdRR175AOfJBlQ0sv+FlCbRf6jZv8C5p+PkM1bHK6Am1uh7ZDZYSxErU+D58ecxaqQrzAiW4/cm6Dk=,iv:NY8TZwHumvKSVyH2IljyZYpjCGwf6BZScJztZt1cltE=,tag:Lg0H3NGW0OSgxxd1CDOZog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
