# Traefik BasicAuth secret for Longhorn UI access. Format: htpasswd with bcrypt
# entries, one per line. The 'users' key is what Traefik's BasicAuth middleware
# reads by default.
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-ui-htpasswd
type: Opaque
stringData:
  users: ENC[AES256_GCM,data:DJOOeiAIS5PjUkKIMBSGnsjXz2Gs21VkJywELGnpe+WskHAGvrqpqrTSNquApvQ95FRbysh5LH7y/7l3nxDAzJ5www==,iv:gZJO5vXP33s666meYE/cV3Vs/mnouVohpRCRFggOg3Q=,tag:C+JhE/ViwzMuze4+ltXSLA==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYzRxZlQ3c21tbW55ZlN0
        SHVOKythekxHTWFvM0JjRjNYZi92a0E1bTE0CjQ0RE1naExFc2tpZDk4ZXpCcFJm
        WmhMeWtBZUtFSlJwWE1rbFpIZ1FnYTAKLS0tIEhHbnl6NFhyTGZPR3NXbkJQYmd6
        d0wyais2V0JwZVl6N2NCRVFjemM5UHcKuipbXJSJGJZafUcM64lVq0Pv87puguM6
        dMt14k9RAjPx8CoITY5g+ueDbHCZ10xzqJnFhUtupNhgzTLJDFtVog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T23:38:35Z"
  mac: ENC[AES256_GCM,data:yYJWQf+xq+QPmIYfDAqRoB/dSSr0loo6dcmkzzOuEkjzkUg9stmeNBYKHg6oJlSkKnJSouDIt2vhplON08xkPlTWXNe49Eez8qO6e4av4Mj6miEgjhi85eHYynUxMzNsmxVbb+cHMpJgquYo9VWaLzVfDRazr9YZ7BtfjF272H4=,iv:XI58xWdKO97nPPtuRgEeRvnbVlrwuY7X/KiW1o4icDo=,tag:503RyAeF2DU5KVW2MG1dWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
