controller_token: ENC[AES256_GCM,data:3QbP15eGClCX7XbcTwr0rgSZXDrc7pXP/lZzxVNMVF1rcm6SAtl0Bms5sa5/PpulnvkGIZIHVFwvoEpYl28eqA==,iv:hO42FQ+xq/BYnfr1uZ78on1tl7aqy9ouGy5SbLkCzhg=,tag:J374z+bZ0QbjGoWmbzVEdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZXZSa3ZNSmo3UVBETXY0
        QTNmeW1JMzJvSTZ2TS9wVmVNSER3TVJseVI4CmxxTTNkQ01YNHRTWlRzQWtURkhO
        RWNmeTcvNjFPajZZbm5ReDNFSlRDc28KLS0tIGNGVXVsOG1EejN1NWdlekRPWGJ4
        Z1cxQXJMbURMYWo5Y1NJUE8yZHlEcnMK/kcfXXSC6U4URtbRRRphOTvxg6AWo4Sh
        FWRXLCvEdnZqDDtT5DQh5lmb+VS3ODyHCTZqyTxjvYmiC1EHbCbGsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
  lastmodified: "2026-09-01T02:20:37Z"
  mac: ENC[AES256_GCM,data:PX/4vCF6jYDLslonmTh2+zbAZlk90NJ6SCcsyyDidvzpXsLkw2JjZIR4/wixFfPi4cUHGySuZ2PZVB0V/SeKteespMgI70pR4tRYXXYObqX1pC/0jQgGOWVTssArWLq3hmoYlmcwzj6blM5WYqxr47Kj2OSYOCJbz7MBSI64nCc=,iv:0JS1OP4GXOcPnt5bca5e9RBapArsES1xupVH18FEjkA=,tag:LJaOpTx1Gr5Xe6BlwtRMvg==,type:str]
  mac_only_encrypted: true
  unencrypted_suffix: _unencrypted
  version: 3.13.3
