---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./lemon-manuals-ai-pv.yaml
  - ./lemon-manuals-ai-pvc.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./networkpolicy.yaml
