---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lemon-manuals
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-lemon-manuals-static
  volumeName: lemon-manuals-ai
  resources:
    requests:
      storage: 2Ti
