apiVersion: v1
kind: Secret
metadata:
  name: grafana-mcp-secrets
stringData:
  GRAFANA_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:m1VosoZAHo8JOW91uADZmtFEIImSWQqi8LVuwZnVneRcJ9RfK3QwQPytdTmd9A==,iv:tEMLVmlmn7SiJs82gcn7xzfJTa/gynx2JrflV5ckXoE=,tag:wOAcmpjIcsU0vc1w/lf0ng==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdTB1Z05FakhXWU82T1Z1
        SG8wRDNDM1NoN0hpcUt6TTkxaVZUK3dQbDM0Cm1HVWNSdXN4OThiRkQvZlkxWXhj
        czFDVTh0OGhCVmYzemoxVnJsSmRHdDQKLS0tIDJ2amhGNzArMU1SaGRtUHFESHRp
        QUhHT1IzLzAxTkFRYTJJUzUrRGFGbmMKUKQm6nBaZ+JTSmJbaVJqjLeY0KpWxxGt
        KkPYsiYwTwv+F04xsAm2QVHjDnpO6Uoy6v/hTsJzEtRuyEkFQ/9p8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T05:52:39Z"
  mac: ENC[AES256_GCM,data:uTy3icfpDpUpGq2nOSgc/2uwLflVLVkBpY1GYatz0ByQkNjkJHjMvTTvw/1+illnsNdueWuamB6Ih7x2kz6Iv3FAto3wgNdTD7R3/X/ApZgVljShLSzmxHifcBu0id6mP7Z8FCLwfovVVqdGbgGi5mSf829GFfterWRyooO5sSY=,iv:hLZEUR97p6c+g8+sXyCaOP1BO2h5I5jcYdt3vQQkhN0=,tag:C59k3/OvSXUTA79gWINtrA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
