apiVersion: v1
kind: Secret
metadata:
  name: grafana-mcp-secrets
stringData:
  GRAFANA_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:P+mTGFGOj4c/7ZU8rFc9qltaj4QlyPXvG4kYxPXtt0706fC6,iv:7bgg5Eq8LgAul/M7VKiXbRRllIYRPacLBJwhHOrMJ4c=,tag:vfXrGaB4yNrucKl1WzIrcw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdTB1Z05FakhXWU82T1Z1
        SG8wRDNDM1NoN0hpcUt6TTkxaVZUK3dQbDM0Cm1HVWNSdXN4OThiRkQvZlkxWXhj
        czFDVTh0OGhCVmYzemoxVnJsSmRHdDQKLS0tIDJ2amhGNzArMU1SaGRtUHFESHRp
        QUhHT1IzLzAxTkFRYTJJUzUrRGFGbmMKUKQm6nBaZ+JTSmJbaVJqjLeY0KpWxxGt
        KkPYsiYwTwv+F04xsAm2QVHjDnpO6Uoy6v/hTsJzEtRuyEkFQ/9p8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T04:53:21Z"
  mac: ENC[AES256_GCM,data:QaB6wQzCobaTDI72ohGM6dOR3dYAUJI9cQAORFFRfYWq+nvMM8oTgnaFDhUwWsdI/H+F9IzB5Wwxd1sv5l/UqzmbCS2K+Z/RMMeINPtuSUQkUm+o2g82a2lrPghPGrlkdRdRMgmOfb3zNY/hYfv6zPOxVA0VXOr97sgsSjyHfzc=,iv:lGybk+z6x0SlPHMtY0Ru/mdUbr8PBeEtuwbFrALP4hI=,tag:YQbH3D3X6ba8DMXu6Z5vBw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
