---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vlagent
spec:
  dependsOn:
    - name: victoria-logs-single
  interval: 1h
  path: ./kubernetes/apps/observability/vlagent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: true
