apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:sd83m9Hiub7piizmGeFUzWDWls+MM/adYQyLtb5PHYZINPLJb7OKanzuml04UPr8GCafxrnqf1SR3uKlt967QlZATA+fbSkW5kkQKaSv91LXGZmgHTQKBE73ax+PO1ax5oFDyZBgzt1DNgzYTYt0z6pD+ncFggoiuU/BUVGK/Kyt2gLkh5n4ut0oqtszU199kfqmaW2XP2DAN/PwmIbQNoWHnVk+PrL12k6NjFIqVmpEJxw/,iv:ki5gqPBwQPbloaXRKaqUksJ1BGWUXPo7V9+JT6fJpTM=,tag:ElNNIjFgW2sBw+lnYYnhZQ==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aFVGaWZjbU1GYU1MZ1VB
        SUZzMkJiUjJqVjB3MGZ1ZjJxc0dRQ05WS25ZCi80aWZBQVZLdmNka3dvSmtrcllB
        UGUwaHVoL0dwdUdJd0p2YWtiall1TzgKLS0tIGRabUV0VGFoemxHNFZRN04wTTk2
        Y3FrNURtT1AxODZnVmk5SGZocjNuM0UKjWw9fWLLX9qZ6xX64SEABg4jwz5r5PuF
        zevbPTa7FCXIGYzuDS575EcUcU0X2Tom3DVnV9+FseMZic4QUdAyKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T22:41:40Z"
  mac: ENC[AES256_GCM,data:WV+ZMuqZMxRX0f4XNN1inWuWvy4VHHjjDUN8g3ukLyAKoogBE/eGxjlL0VWpY4E9A0GfGUgQBHsW+nffA3qETVGEJ29KydXiIcESDy/uGBB1BfeQgtCUqvZaFRAcfbEwYASJX6GMHB89pnIGhqCM15yjO8xL15ktE7x7aVx7QIk=,iv:WyKfIastgMgZuNN5QQAArCvQB85UKgN+cccL/JWaF0I=,tag:3mNw8+qRLc8TG4s2wmEGgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
