apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:bmj9jZT1mbzXVa7/BiAPAkyRnO2yyADBLkvIjPuOqlXmZNnr756LYDTy/FQTADw6m2XL2sIpqBP/G6KNOtpYI0Cf2U9Y4m8JgwUra5qrRiU4Y8VKWSfIAV/A2krTyJuhl1SnhA+SrRBLq1AZ94CASwLy0FMtuzlSeZxFC9NqXeXcdtDxt7ShpTAGsC5lAFrVHxc71sLrGbLFlH+CJTXO2nJGadF+DWxysiQie18AvwsuZRPS,iv:u0jzYWK88PQxlk5ebtHbBB65yqwmGZv9j8sHm2EJrzU=,tag:fXtDBR5vFAdhmhHFSIyqgg==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNSt6N3JFWkRFY1JLSDVE
        bldHK1hta2NjVG1iTkUzaFJYd3E5Wi9ad21FClkvNlVLTmVoSEVncHRDdFVHRFRD
        b2trU3BXRTVEZFdsOHhSVG9DTDFuMGcKLS0tIGxaNUlON096QUQzcXlmVG95enN2
        b21HTjJkNWVNNVBlN0lJeE1YdlIvaTAK+KE9GnRXXzSCRyadFVIbAwTQ9lboV5bL
        /NeE/sI2y/VqHyGkIdxs3433buvLWaSOzHp6VmBYlZhuZLyJU5JrLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T23:34:25Z"
  mac: ENC[AES256_GCM,data:03w29OhuUswiXCVpUWuUvEE5oTIT99roCWuYBEwgfZwSRY0Hz+wbT6bEJhWT9MsjQ5pyal7dzpPx5WzVpjwK2kjvf/XK9As3oIXX74tvQ8HPM3ZvFec1HLKpnxKh272l3atGpsI6xBAYehBfTUYttIT/+HABxWM02WHsl0IVjCo=,iv:LYe6ikG1ZvV2yrlXUMM1VxEv6jJvGPhrctA06fts1UY=,tag:ATapbs4Cn/r3Uo1izhOgaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
