---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./dbhub-mcp/ks.yaml
  - ./digikey-mcp/ks.yaml
  - ./flux-operator-mcp/ks.yaml
  - ./grafana-mcp/ks.yaml
  - ./kubernetes-mcp/ks.yaml
  - ./metamcp/ks.yaml
  - ./playwright-mcp/ks.yaml
  - ./playwright-stealth-mcp/ks.yaml
