---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/pod-quota
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./networkpolicy.yaml
  - ./digikey-mcp/ks.yaml
  - ./flux-operator-mcp/ks.yaml
  - ./grafana-mcp/ks.yaml
  - ./kubernetes-mcp/ks.yaml
  - ./lemon-manuals-mcp/ks.yaml
  - ./markitdown-mcp/ks.yaml
  - ./metamcp/ks.yaml
  - ./open-meteo-mcp/ks.yaml
  - ./pcbparts-mcp/ks.yaml
  - ./playwright-stealth-mcp/ks.yaml
