---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-imports
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-media-static
  volumeName: media-imports
  resources:
    requests:
      storage: 50Ti
