apiVersion: v1
kind: Secret
metadata:
  name: metamcp-secrets
stringData:
  #ENC[AES256_GCM,data:gWLfcLnJMQYp6SnibtOPre7GIJFrsNURP/v0Ul/nX+vOKy1/cPlaSxjVTjgQp+JfHlLI5mQwmX2aGyuVaI/51ZC0J729zdx3,iv:qP0nnlGhZiZi866FBpkf/ywVEz1SCdR5kK3zM6Dyxb0=,tag:QHhsFB9e5AYrF222OT/AXQ==,type:comment]
  #ENC[AES256_GCM,data:V7Bx2nRiwNiHZg4yOvduamgIPuYNUJXk2cSAUe5ZgOkvCPrRm0nXNY3MTb2fMvS5hsMGhLRIKA==,iv:BVrEAVmhDT3g1EdFa1dXk0w8fMkTg9E2gYOYWMBBE9Q=,tag:bmbnGrWjwKVYcv5zt+C7vw==,type:comment]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:H2eX2XPMtkDARaIv1hw9lolN0janTuYa0KtQi6JIJcB9lq1DuP4F2wGoxSgUcR6zNP3O3kjMAN2+w0pe+BaScw==,iv:wfTFoc9jetPLYWEvpNUY7ICqh1/mbJrY6m8UK9O3TKI=,tag:Vxyy3bQpi265JWgaXTAYBw==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdURpcG5GckhlL3F3Nml1
        QXZPMit4dTEwNkRrOHBSbDY1MzVvK2ZSZjFVCll5TDJ0c1BoNmNyZnFWdkRBNFZY
        ZU4rcURzNmlTSzkxcExjL2JqUmZUSjgKLS0tIDFkY2U4S2pER3NmNUFjd0Y4UHN4
        MDl5R2VBeWJ0ZHNNVUp1UXk4Z0VxdFEK0Ur4e1jvd6hXzyC9X1KyXQuvlxkEqQqC
        fLjIxnnwaHp4JZP10asSIq5Q19rwlTZ/LEhS0vjJsbBjQ/Zk+Ie14A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-30T03:50:35Z"
  mac: ENC[AES256_GCM,data:flRoeFWLHMMIOuKsipT5Ip1pw2DyVlvyr3cNZ8yZztGs1aY4AYkQCMYtkr036scFTmnNUyExl8YV7pMLPJKvFV8IbiPF+3aimUJ9Ur+UJ+kZbyUaFuAfuwqBModn5tbpZKB2lDGrkdqf/i+KEkBdE2ITzAz8+rkU70xOeNu5bU0=,iv:9U6Grzi6HD0OWXfN/1CMruJAqenUgrRn+2fcxjnOclo=,tag:xyCJHPzIYkymuuR2C/eP/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
