apiVersion: v1
kind: Secret
metadata:
  name: bgp-md5
  namespace: kube-system
stringData:
  password: ENC[AES256_GCM,data:cF34oX0XzfnQqcDd9mnianr5OrM8qS5dhOcGRbz9TNE=,iv:pTjiSJSi2gdWKxs9KrOIkGXnypF11ZW3Y9Ij2WqEXKU=,tag:UoI2m8FvJOotgOsB8otyDw==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQVZiVk16T0VBSEZJcGpi
        R3RQei95dVJDUzZIUTNnNGpYNnZiSUt6SVhRCnIrYlZrdExJT2tSVzlkcXlCWWFv
        ODcvVE5rZ3c3VW1UWE1ZcHYzbXJpNFEKLS0tIEJVQ2JlWUF5UVFOaVNCNktoK1Ni
        UjM3R3gwZmx2ajNqQkZNTmZYUkFFbVUKe5KqTFWe9DgsEPbAZpDWJjtJmrP+N070
        hKjPNtx/LwnVjlqYZhoOorXnNHMmVRDgNjT359qjAz++clJC+xHpgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T01:06:15Z"
  mac: ENC[AES256_GCM,data:4gg2iLdfGX3DidTTu5z2CtATUdddANBpqZqN65l78aPmx7lMEkL5wnbgyTuAzm0vlCVhRurMY8jqYaAyqgGQlMHfv2K6yaHOtDWHgupK3M0XpQLu90AUm1LNM143aWpju1zoilGMYu0jl0dgODdzfezMi8MLsDk+5hAtIbj1aqA=,iv:Iy/D9eBpTVrtxTxqessgOk8roH36h37hyaFsgnur6K4=,tag:YA1xYXBLb2XaRJW0ETFlOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
