apiVersion: v1
kind: Secret
metadata:
  name: dbhub-mcp-secrets
stringData:
  METAMCP_DSN: ENC[AES256_GCM,data:JfdN5y+5r/lFJqRJr9AS0pDuk/DXplws5+OiZ6vqAjzOMgWbd/9kS6MyYd6huEoLR68t/OCkjUB3oDqAU2pCiBHpNIAwb/8A3B0hZ9NsdIRS0drqrk9IAkOgXcYvQDcgMRLq8jy/JOYIM9Q=,iv:d2JyeMXYNLHI7RQDl4Vwz7xrrh9Grb5C4hyb4Ggy7yc=,tag:wVC468FB0vjYwlp6fFMD8A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYnRONko5NTNxaVEvSndn
        d2c5RmdSZ1JtTDExWGtnK21sd0pBRFdjWVVZCkNnOUhaRTRsS09Td2Uyb2NoOWtM
        ejdrWXFFQll2OUZCd202bjhwdmpnYTQKLS0tIEFNTWptaXJUc0ZYVWFsOWZjcytT
        WUp1clkxSUFQbkFYRndhK0hlcEVYUkUKbl/fKbB1eFz/WEZ0dSOYNak7exHx1tJk
        QTDOkRINSAWiLwmJjfuytk7y6Fm9RFPNfPve7dUXWSqSQ1ZtCN4AOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-23T04:38:41Z"
  mac: ENC[AES256_GCM,data:gSXUv61wsTGPpOuqILzofYvXfKuBG7Z4LN5ZyApA4J6fXPmyfwOFlfZNlr3ZQ8WFjfA1ckJ9fYOiBj5cjvWCGuZ1cMeB3lJFBekGUmu5ynWf/siwkP6QBToS8nTqPI8VlzNvTZTjbZfcxE1rAVzpzlsZsoV4s4/29PPCyUCRmEM=,iv:AkTje3pUF3l86D0TeYhJdrcBPdsdYiT9zXskK6lwU/Q=,tag:QDoZUf5G6gIEkMDmhB2Hew==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
