apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:g50kAJS3kWWlh5mAjDY9xrEeC90P59xlbqfNaS/5h9OH1tQ4wtuMA5gLeLKqbNKCjrJxT+Y=,iv:ecDCmHKWSM/JqN3dY/OeaicuzkOksWemuRphUHGR4zk=,tag:a8tfxAqiPJ6abzc5uMcckA==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3STN2WTVud0N6SUsvUmlF
        VUZQNzZYdXZLZFlKb0UxM1U0MG81QmR6Vmc4CnVEUDlFMjV4Q1JkUmxQL01jdjFh
        NDJCblIwVHZBcHBHU2pmWm50VGhlL28KLS0tIEJlMkxyZnpOemU5bDdNUGhuSWFO
        WFdIYUQ2eGZDZ1hpaE9YSWMzcDAxRjgKCTxzAfMXOL00XB1lVKjTlTbXjqVU2oTv
        urv3+1fr2XZNjhL2JrTSXM0vgcwC4lS5eykxVy2fNDAYB5CLRorG1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T22:41:40Z"
  mac: ENC[AES256_GCM,data:Vbi/NkQWTcexqI/iC6d/RyAopNxJe49whKW2Y+E501m2YvmfV4yRfBz+cCRmeRs8cXz/nDLRQMx/rUIkEdCbKkVkuM4LP3wyNzkf67n86Ef2D3o6ys1B2RiGujyWlDTUaCn3S3Sc20tlqg0heVs5yM9hwpoqO0wtr8DwLSTfuNo=,iv:UkQRHK9gQqZ/OMdT/H//zBXXBGbGTia1znjS+KIkm9w=,tag:7GCGJhgKkAqYzr85AY3uZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
