apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:H5iNV/mETr/LFJBoXz4+9+XNouHKmDEZI+pV+lnM+vT4wMPcztt/8ZWoI8VsGV+AQvCxje8=,iv:neJWn5NekbEoxzyrmt7/M/QgazERL6+kEKK0ub9+erU=,tag:4jL7CHfFuiWin0NuuEN2+g==,type:str]
sops:
  age:
    - recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y2lzanFzN2JEdk1keEFh
        TDR3Y3B6cmtjY0pBYjZwQ2x0WFBtdnFJdzIwCnhTRElJM2w4WFR2bU42Q21PL2FR
        eng1Y2xYTTkwenNMbEF2MDg4WTY0UWsKLS0tIG8rUEozUzlTRS9WVFYweXU0Yk9B
        R2RqaEhydHFkV1Z0aXdvc0VTcU1acjgKN/8ViPQDN7ogyUoCWUSuntmJ/Yw0CynO
        elbistiaqnosl0EBolPCRXTSQipE9Y9qZTqlpR0fY2dAJDKdc3UVig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T23:34:25Z"
  mac: ENC[AES256_GCM,data:yqA1nFXSNJpaaf05aGncvEG22HyI2N714NCkTQm7aTeAq6l7UrugeGpogpGtApo628/R3/gQV0X+YNkHxPfGebJ/0RnGVjAyO2qUdnbowZzXPsJrnxHQX9Qtx1OGMZt6KAhnK6PY3pHtJIAujQCN6ooW1GcXjDxH+wQ6zn5RQdQ=,iv:kSYPrEogqlm1lMOwGMjU2CxI3my47RPSQfzg3HvK5iU=,tag:d8bYrUEY68Oo5ZOCgmejKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
