---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lemon-website
spec:
  dependsOn:
    - name: lemon-manuals-storage
  interval: 1h
  path: ./kubernetes/apps/lemon-manuals/lemon-website/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: lemon-manuals
  wait: true
