---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
spec:
  dependsOn:
    - name: multus                 # NetworkAttachmentDefinition CRD provider
      namespace: kube-system
    - name: whereabouts            # IPAM behind storage-network NAD
      namespace: kube-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./kubernetes/apps/longhorn-system/longhorn/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: longhorn-system
