apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:/Pswzf/PstO5BMOSW0GrhQh2f3QOSOUEVr7IBLrv/1s=,iv:5OG5FL0b1xfeb/DfdS3vAeHu9qHMIC+sj2e0Llrmqeg=,tag:+8qZSgOnbawKUpkety8CIw==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:NbyKVcEXOfOiBTeWhFixSyixQaxj9xnT6aHQlbMNnhQ=,iv:k9p3rrcwgGv+Rfjh6FxNgKBn9l4/7QrdNKMIo50IyrY=,tag:vkBuYQPsuZ72sP3hJY97EA==,type:str]
  HOMEPAGE_VAR_LIDARR_KEY: ENC[AES256_GCM,data:auPqwzCPRUF/JWJh461bMTJEIYpXilYxNjRk5j0heto=,iv:EaaFI3wP4X/+1R807njFw8QpSyks3XPyOx9FzXoHrA0=,tag:SPAp8IuibXqOC89VIOCyOA==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:S365YS5g/ui0FDoKQScNdPHLtSVMEn41y9BosdDJ650=,iv:w5zgbCWWU3fWpN9xf69MkgnMuA6GUzNHvtvypN1ItqM=,tag:xbRcFt/P1vWgTBSVwmlelA==,type:str]
  HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:Bn72XGtuJy3gf6eHLj+0TyGuPBodpmyoqg+bVWdWSYM=,iv:0wlkn+0urbYk2gsDUu7Ay93lp1gmfsAVdO/RA0LkfFU=,tag:rsCPYh7WHUohaENCbPO0rg==,type:str]
  HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:5+bi/6dq6d3m2Zj2lO9jK2bvTls+JaknvSErdeVCoZo=,iv:DECnU7Mbn/RXYw8ExtSOemHwiXekPXlcZuycmXcPe40=,tag:IPKvHeFodGlwezrq0AgGCg==,type:str]
  HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:N42btJYhThvFA1gc++6eCllcwCdTVip/T+WOZ27RXxDMfnb1XtELTgZQrUziGWoGG2MG9pi1R8TauMs+IYJkwlx8+R0=,iv:EQFhcvGc1qYsm6WnUWKBzZTQ663qAith9YT9d8FGfmI=,tag:eiMHSw+3lhl7AInhd+w8lQ==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_KEY: ENC[AES256_GCM,data:18Wa1R2WZX+vf3lw11CHEhPyjwa1S9dwBob7lA+Lnvs=,iv:MZ1yMQU2wwmKPo9Ab+dyVdYklNYyc/3Q12yqtMLdZAo=,tag:mC61+bCHdh/p8ATEEHkowQ==,type:str]
  HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:V0gHX7JeOjT+vVCHl2mHwezGye0UhPcIAu6rU+h1Z0k=,iv:a25DjDwwQ6NKKpWOL70Qpnql4QJmF0E6mNuQ4LuSJ6o=,tag:rzoeAB+EjJjDBJosv4UMrA==,type:str]
  HOMEPAGE_VAR_PVE_TOKEN_SECRET: ENC[AES256_GCM,data:PMgHv3gcqUc/w9VmOvymY60F8cCcug8bEWKg4TinfyXFglOQ,iv:Uu7DTGKWnLVOM6U5JHFFUE7Mlzh9Q+3jtRbLW3tlLWU=,tag:7RWyHDCDTVxXNe5xSWu5rA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT2cxbkRoRXZzTjJsZ1Zp
        Sk9ISlhTcGFWdmIvRFpySWltVGNKcG1FSHpBCkNydFB5VnBSckNiNHFKUHNRUzVZ
        Yk51ZnM4ZEJselhST3FjR0I1dCtFZ3cKLS0tIC91SWpndnZ1OGt6MTRPaEFSM3RF
        aU9CcmRzWmZTVmpVMkZHc05WZGx4SDAKh5ze4w1IOx2z8jfxs8CW9DchHGPCmUx7
        YrAuYdFTMOcMCtOv4LZd3E2VKmmqOFWQ55GxeZKIpxA0m1K8BYdJtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T23:41:45Z"
  mac: ENC[AES256_GCM,data:ZFoO2wOdKEUTewfQ+n1x435MI6JySbbu1Ev4twXkZmpY7Wyn/Q5XwTX/4SK2YT6vm2NNUaQF5WBnJAIwENfyPAfbGJftTXRgEuer9IOs1XJt8zRhdB2eKkkOpk7EHQciBCfblxtFvBD3EcA+b5k2205MerJgDLZn/JFo5tWlumc=,iv:00AAUyIZui/LdyW6BmtTsA+qAX0wIHchLXF4c4cDxtY=,tag:uz4oT9FTcxpiQ1ehpo4rSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
