apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:/Pswzf/PstO5BMOSW0GrhQh2f3QOSOUEVr7IBLrv/1s=,iv:5OG5FL0b1xfeb/DfdS3vAeHu9qHMIC+sj2e0Llrmqeg=,tag:+8qZSgOnbawKUpkety8CIw==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:NbyKVcEXOfOiBTeWhFixSyixQaxj9xnT6aHQlbMNnhQ=,iv:k9p3rrcwgGv+Rfjh6FxNgKBn9l4/7QrdNKMIo50IyrY=,tag:vkBuYQPsuZ72sP3hJY97EA==,type:str]
  HOMEPAGE_VAR_LIDARR_KEY: ENC[AES256_GCM,data:auPqwzCPRUF/JWJh461bMTJEIYpXilYxNjRk5j0heto=,iv:EaaFI3wP4X/+1R807njFw8QpSyks3XPyOx9FzXoHrA0=,tag:SPAp8IuibXqOC89VIOCyOA==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:S365YS5g/ui0FDoKQScNdPHLtSVMEn41y9BosdDJ650=,iv:w5zgbCWWU3fWpN9xf69MkgnMuA6GUzNHvtvypN1ItqM=,tag:xbRcFt/P1vWgTBSVwmlelA==,type:str]
  HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:Bn72XGtuJy3gf6eHLj+0TyGuPBodpmyoqg+bVWdWSYM=,iv:0wlkn+0urbYk2gsDUu7Ay93lp1gmfsAVdO/RA0LkfFU=,tag:rsCPYh7WHUohaENCbPO0rg==,type:str]
  HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:5+bi/6dq6d3m2Zj2lO9jK2bvTls+JaknvSErdeVCoZo=,iv:DECnU7Mbn/RXYw8ExtSOemHwiXekPXlcZuycmXcPe40=,tag:IPKvHeFodGlwezrq0AgGCg==,type:str]
  HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:N42btJYhThvFA1gc++6eCllcwCdTVip/T+WOZ27RXxDMfnb1XtELTgZQrUziGWoGG2MG9pi1R8TauMs+IYJkwlx8+R0=,iv:EQFhcvGc1qYsm6WnUWKBzZTQ663qAith9YT9d8FGfmI=,tag:eiMHSw+3lhl7AInhd+w8lQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT2cxbkRoRXZzTjJsZ1Zp
        Sk9ISlhTcGFWdmIvRFpySWltVGNKcG1FSHpBCkNydFB5VnBSckNiNHFKUHNRUzVZ
        Yk51ZnM4ZEJselhST3FjR0I1dCtFZ3cKLS0tIC91SWpndnZ1OGt6MTRPaEFSM3RF
        aU9CcmRzWmZTVmpVMkZHc05WZGx4SDAKh5ze4w1IOx2z8jfxs8CW9DchHGPCmUx7
        YrAuYdFTMOcMCtOv4LZd3E2VKmmqOFWQ55GxeZKIpxA0m1K8BYdJtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T22:16:31Z"
  mac: ENC[AES256_GCM,data:KHRQd+68HOhhz/4bB9qySsoLU7VVtR8pSb1cdNWrMwDcaAVjzmwJ7stKW1YKo4uCPM/Tq6z8iqGT5MPrwMPrR4duxTdYFnl7GUXFeabQtaQi0L85xi1k2kjyrtvTcpBqM26lsZKLZLvbRC9azkEAzlkkSdXDU4HUftPEpTdHTZQ=,iv:QLWc2O5sv5r49fRryqqy9aZ+hTSiy18gvRBwn1WsKeY=,tag:/DdtDXSNMb7fWhCesT+I+Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
