{
 "title": "smartctl_exporter",
 "description": "prometheus-community\r\n/\r\nsmartctl_exporter\r\n",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(smartctl_version,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SMART General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (node, device) (smartctl_device_temperature{node=~\"$node\",temperature_type=\"current\"})",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "smartctl_device{node=~\"$node\"}",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "Average temperature by drive type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (device_type) (\n    label_replace(smartctl_device_temperature{node=~\"$node\",temperature_type=\"current\",device=~\"nvme.+\"}, \"device_type\", \"nvme\", \"\", \"\")\n    or\n    label_replace(smartctl_device_temperature{node=~\"$node\",temperature_type=\"current\",device=~\"sd.+\"}, \"device_type\", \"sata\", \"\", \"\")\n)",
     "legendFormat": "{{device_type}}"
    }
   ]
  },
  {
   "title": "Power on Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (node, device) (smartctl_device_power_on_seconds{node=~\"$node\"})",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "Device Media Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (node, device) (smartctl_device_media_errors{node=~\"$node\"})",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "Power Cycle",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (node, device) (smartctl_device_power_cycle_count{node=~\"$node\"})",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "Error Log Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (node, device) (smartctl_device_num_err_log_entries{node=~\"$node\"})",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "Drives failing SMART",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(smartctl_device_smart_status{node=~\"$node\"} != 1) or (0 * count(smartctl_device_smart_status{node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "SMART Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "min by (node, device) (smartctl_device_smart_status{node=~\"$node\"})",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "SMART Current Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (node, device) (smartctl_device_smart_status{node=~\"$node\"})",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "Drives with a critical warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(smartctl_device_critical_warning{node=~\"$node\"} != 0) or (0 * count(smartctl_device_critical_warning{node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Device Critical Warning",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "max by (node, device) (smartctl_device_critical_warning{node=~\"$node\"})",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "Device Critical Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (node, device) (smartctl_device_critical_warning{node=~\"$node\"})",
     "legendFormat": "{{node}} / {{device}}"
    }
   ]
  },
  {
   "title": "NVMe Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "NVMe Data Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (node, device) (smartctl_device_bytes_read{node=~\"$node\",device=~\"nvme.*\"})",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "NVMe Data Written",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (node, device) (smartctl_device_bytes_written{node=~\"$node\",device=~\"nvme.*\"})",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "Available Spare",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min by (node, device) (smartctl_device_available_spare{node=~\"$node\",device=~\"nvme.+\"})",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "Available Spare Threshold",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min by (node, device) (smartctl_device_available_spare_threshold{node=~\"$node\",device=~\"nvme.+\"})",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "NVMe Endurance Used",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (node, device) (smartctl_device_percentage_used{node=~\"$node\",device=~\"nvme.+\"})",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HDD Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Errors Corrected by ECC Delayed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum by (node, device) (rate(smartctl_read_errors_corrected_by_eccdelayed{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "Write Errors Corrected by ECC Delayed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "sum by (node, device) (rate(smartctl_write_errors_corrected_by_eccdelayed{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "Read Errors Corrected by ECC Fast",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum by (node, device) (rate(smartctl_read_errors_corrected_by_eccfast{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "Write Errors Corrected by ECC Fast",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "sum by (node, device) (rate(smartctl_write_errors_corrected_by_eccfast{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "Read Errors Corrected by Rereads/Rewrites",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum by (node, device) (rate(smartctl_read_errors_corrected_by_rereads_rewrites{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "Write Errors Corrected by Rereads/Rewrites",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "sum by (node, device) (rate(smartctl_write_errors_corrected_by_rereads_rewrites{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "Read Total Uncorrected Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum by (node, device) (rate(smartctl_read_total_uncorrected_errors{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "Write Total Uncorrected Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "sum by (node, device) (rate(smartctl_write_total_uncorrected_errors{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    },
    {
     "title": "SCSI Grown Defect List",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sum by (node, device) (rate(smartctl_scsi_grown_defect_list{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{node}} / {{device}}"
      }
     ]
    }
   ]
  }
 ]
}