apiVersion: v1
kind: Secret
metadata:
  name: pcbparts-mcp-secrets
stringData:
  MOUSER_API_KEY: ENC[AES256_GCM,data:2vgt/Hkv1xT0xppACNK8HytaQ+doy7gjxa6+qZ1bAqDasw==,iv:A6HGbmKqtBWZZ8jtxgN8l1Rxlxo8/OqKLWxUBGCLIFE=,tag:cRB3lVbMBFfKm+BuzziiEw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdnExZE1HVno5Q1dveCt0
        ZU1zYmszY0swK0dpWnNVbEREa3VFRmNKWDFBCjVrQnZ5cytaZzV5bEZzbUlMOVQ5
        ZTNSRUh2WjZQYnlWbko2eVd0SEdYamMKLS0tIHljQSsrTWpwUnFROUkzbUNJVDUy
        OGl4NnN3dzNyMVU0MzRhZGZqbUFjN2cKPjoBmoTncEd+CoDs7FqxO6dHdXLxyO65
        OvdWuUqX7M1Pb0YAIZW21Ml1l+nTVedN8xLEJll5u9OnSJNZA7nLXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-23T04:59:57Z"
  mac: ENC[AES256_GCM,data:HkzW2GluQ+llmFCPEe89LBCWvuLjdg5btObbtPVgx6SeHRQ+KVKmTf6XKFZIjYcqBY0c+EVh9Oem/YwHr24ulchHl6eXw3dWxjwmgBpZEq7cFYooQUl7PZtljX511PH1VLIn1HCnkWcq0uMPoYbeKPJHs6b0Dq1Czsnr6+1A0qs=,iv:Pq+BdXJVvNvT4qitf7B7N5NH+g2L1hUxlAXEznH5gF8=,tag:J3qjqEBjeUtVqHcsdEbAqg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
