apiVersion: v1
kind: Secret
metadata:
    name: pcbparts-mcp-secrets
stringData:
    MOUSER_API_KEY: ENC[AES256_GCM,data:H2zbKFszfjIL21N6D799VEALmtLtekUUOqouTq773oK7ht33,iv:EdWJGaL5ep9WHs+32erkcybqupA/v4vaZxPxdsu1x5I=,tag:P6uNcUS8Y6QIH0uAxUkRug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdnExZE1HVno5Q1dveCt0
            ZU1zYmszY0swK0dpWnNVbEREa3VFRmNKWDFBCjVrQnZ5cytaZzV5bEZzbUlMOVQ5
            ZTNSRUh2WjZQYnlWbko2eVd0SEdYamMKLS0tIHljQSsrTWpwUnFROUkzbUNJVDUy
            OGl4NnN3dzNyMVU0MzRhZGZqbUFjN2cKPjoBmoTncEd+CoDs7FqxO6dHdXLxyO65
            OvdWuUqX7M1Pb0YAIZW21Ml1l+nTVedN8xLEJll5u9OnSJNZA7nLXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14wcg0t6njf76c4ctrndypvvmxk9p7jkumnumlvxdmsn543tc3yusgk5jwy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T05:04:53Z"
    mac: ENC[AES256_GCM,data:BlbkRP+tzABzSfvG5MUh8yMh441RpJhDEGlEepoiY933dhjp8AA+xUBvGCUdkaLnRWhZBXGALu/c+2acS8ntDRYOOeBbyWVNQ5BAL7Cy5heCl+Q3WpYvJ6ZqmuTgtfBP2uDhj63TWr78GVLXFDgYl9tUQkjuHA9KGYhm1pdd9YE=,iv:jxMIrPUa1mX3ICEl/djki8dmABRKMdvzLkE/uPBwrIU=,tag:+iHT3exaimdT/ECXf3e/Ig==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
